specs: update to apps/v1
I was trying to play with examples at [1] and found out
they are no longer working with v1.16:

> $ kubectl apply -f https://raw.githubusercontent.com/openshift-evangelists/kbe/master/specs/deployments/d10.yaml
error: unable to recognize "https://raw.githubusercontent.com/openshift-evangelists/kbe/master/specs/deployments/d10.yaml": no matches for kind "Deployment" in version "apps/v1beta1"

The reason is, per [2]:

> The v1.16 release will stop serving the following deprecated
> API versions in favor of newer and more stable API versions:
> ...
> DaemonSet, Deployment, StatefulSet, and ReplicaSet (in the
> extensions/v1beta1 and apps/v1beta2 API groups

As per recommendation in [2], let's switch to `apps/v1`, available
since v1.9.

This patch was generated by

> for f in $(git grep -W -l apps/v1beta1); do
>  sed -i 's|: apps/v1beta1|: apps/v1|' $f;
> done

[1] http://kubernetesbyexample.com/deployments/
[2] https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>